name: Build Electron App

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application (portable)
        run: npm run dist:portable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # To disable code signing for trial builds:
          CSC_SKIP_SIGNING: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

      - name: Create GitHub Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          artifacts: "release/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
